services:
  postgres:
    image: ankane/pgvector
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8g

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres


  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/eslint.config.js:/app/eslint.config.js
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js

  backend:
    build: ./backend
    environment:
      - WEBPAGE_URL=http://localhost:${PAGE_PORT}
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - FASTAPI_SESSION_SECRET_KEY=fcc_advisor
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./backend:/app
      - tmp_data:/tmp/ 
    depends_on:
      - postgres

  server:
    image: nginx
    volumes:
      - ./nginx_conf:/etc/nginx/nginx.conf
    ports:
      - "${PAGE_PORT}:80"
    depends_on:
      - frontend
      - backend

volumes:
  tmp_data:
  postgres_data:
